[package]
name = "person"
version = "0.1.0"
authors = ["Graham Ollis <plicease@cpan.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["dylib"]

[dependencies]
